[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 1

  [[main]]
  identifier = "posts"
  name = "文章"
  url = "posts"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "画廊"
  url = "gallery/"
  weight = 3

  [[main]]
  identifier = "about"
  name = "关于"
  url = "about"
  weight = 4
    